---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      name: scheduler
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: ghcr.io/elmarx/scheduler:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader
  labels:
    app: scheduler
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - watch
      - get
      - update
    resourceNames:
      - leader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: scheduler
  name: leader
roleRef:
  apiGroup: ""
  kind: Role
  name: leader
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: leader